name: Filter Proxy List

on:
  # Run manually from the Actions tab
  workflow_dispatch:
  # Run on schedule (every day at midnight)
  schedule:
    - cron: '0 0 * * *'
  # Run when ProxyList.txt is updated
  push:
    paths:
      - 'rawProxyList.txt'

jobs:
  filter-proxies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Create filter script
        run: |
          cat > filter-proxies.js << 'EOL'
          const fs = require('fs');
          
          // Read the original file
          const data = fs.readFileSync('rawProxyList.txt', 'utf8');
          
          // Split the file into lines
          const lines = data.trim().split('\n');
          
          console.log(`Original file has ${lines.length} entries.`);
          
          // Create a Set to store unique entries
          const uniqueEntries = new Set();
          
          // Process each line
          for (const line of lines) {
            uniqueEntries.add(line);
          }
          
          // Convert the Set back to an array and join with newlines
          const uniqueLines = [...uniqueEntries].join('\n');
          
          // Write to a new file
          fs.writeFileSync('ProxyList.txt', uniqueLines);
          
          console.log(`Filtered file has ${uniqueEntries.size} entries.`);
          console.log('Duplicates removed:', lines.length - uniqueEntries.size);
          EOL
      
      - name: Run filter script
        run: node filter-proxies.js
      
      - name: Commit filtered file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Add both the filtered file and the script
          git add ProxyList.txt filter-proxies.js
          # Check if there are changes to commit
          git diff --staged --quiet || git commit -m "Update filtered proxy list"
          git push
